Repository MergePing/NamHoJung, pull requests merged in 2024-11, with the labels that each got.

#29 [FEATURE][FrontUserManagement]관리자 유저 상세조회
  src/main/java/com/ohgiraffers/mergyping/user/controller/UserController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/UserMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/UserService.java
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/static/css/adminmanagement.css
  src/main/resources/templates/user/admin/adminmanagement.html
Labels: feature

#31 [FEATURE][ConnectDBToMypage]DB 연결을 통한 Mypage의 닉네임 자동화
  src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/MyPageDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
  src/main/resources/mappers/MyPageMapper.xml
  src/main/resources/static/css/mypage.css
  src/main/resources/static/css/mypageinfo.css
  src/main/resources/static/images/mypageimages/background.png
  src/main/resources/templates/user/mypage/user.html
  src/main/resources/templates/user/mypage/userinfo.html
Labels: feature

#36 [FEAUTRE][ADMIN_USER_DETAIL]유저목록 비동기. 탈퇴 기능 미완
  src/main/java/com/ohgiraffers/mergyping/user/controller/UserController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/UserMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/UserService.java
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/adminmanagement.css
  src/main/resources/templates/user/admin/admin.html
  src/main/resources/templates/user/admin/adminmanagement.html
Labels: feature

#38 [FEATURE][NoticeModify]공지사항 수정, 게시판 구현
  src/main/resources/static/css/notice/notice.css
  src/main/resources/static/css/post/post.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/images/post/best-dark.png
  src/main/resources/static/images/post/best-none-dark.png
  src/main/resources/templates/notice/notice.html
  src/main/resources/templates/post/post.html
Labels: feature

#37 [FEATURE][FrontPersonalInfo]개인정보 프론트 영역 구현
  src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
  src/main/resources/static/css/mypage/mypage.css
  src/main/resources/static/css/mypage/mypageinfo.css
  src/main/resources/static/css/mypageinfo.css
  src/main/resources/templates/main/main.html
  src/main/resources/templates/user/mypage/user.html
  src/main/resources/templates/user/mypage/useractive.html
  src/main/resources/templates/user/mypage/userinfo.html
Labels: feature

#46 [FEATURE][ConnectDBMain]메인페이지 베스트 게시물 DB 연결
  src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/MainMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/MainDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/MainService.java
  src/main/resources/mappers/MainMapper.xml
  src/main/resources/static/css/mainpage/mainpage-darkmode.css
  src/main/resources/templates/main/main.html
Labels: feature

#55 [FEATURE][ADMIN-USER-DETAIL]유저 검색, 유저 탈퇴 처리, 유저 닉네임 수정하기
  src/main/java/com/ohgiraffers/mergyping/user/controller/UserController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/UserMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/UserDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/UserService.java
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/static/css/admin/adminmanagement.css
  src/main/resources/templates/user/admin/adminmanagement.html
Labels: feature

#49 [FEATURE][FrontActiveRecord]활동기록 프론트 영역 구현
  src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/MyPageDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
  src/main/resources/mappers/MyPageMapper.xml
  src/main/resources/static/css/mypage/mypage.css
  src/main/resources/static/css/mypage/mypageactive.css
  src/main/resources/static/css/mypage/mypageinfo.css
  src/main/resources/static/images/mypageimages/rank-1.png
  src/main/resources/templates/main/main.html
  src/main/resources/templates/user/mypage/user.html
  src/main/resources/templates/user/mypage/useractive.html
  src/main/resources/templates/user/mypage/userinfo.html
Labels: feature

#58 [FEATURE][SequrityLogin]로그인 기능 구현
  .github/team_resources/db_script/MERGYPING.sql
  build.gradle
  src/main/java/com/ohgiraffers/mergyping/auth/controller/AuthController.java
  src/main/java/com/ohgiraffers/mergyping/auth/model/AuthDetail.java
  src/main/java/com/ohgiraffers/mergyping/auth/model/AuthDetails.java
  src/main/java/com/ohgiraffers/mergyping/auth/model/service/AuthService.java
  src/main/java/com/ohgiraffers/mergyping/common/Gender.java
  src/main/java/com/ohgiraffers/mergyping/common/UserRole.java
  src/main/java/com/ohgiraffers/mergyping/config/Application.java
  src/main/java/com/ohgiraffers/mergyping/config/AuthFailHandler.java
  src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/SignupController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/SignupMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/LoginUserDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/SignupDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/UserAuthDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/SignupService.java
  src/main/resources/mappers/SignupMapper.xml
  src/main/resources/static/css/signup/signupMain.css
  src/main/resources/templates/auth/fail.html
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/main/main.html
  src/main/resources/templates/user/etc/etc.html
  src/main/resources/templates/user/etc/etc2.html
  src/main/resources/templates/user/signup/signup3.html
  src/main/resources/templates/user/signup/signup4.html
  src/main/resources/templates/user/signup/signupConfirm.html
Labels: feature

#63 [FEATURE][ADMIN-SELECT-NOTICE]관리자 공지사항 전체 조회
  src/main/java/com/ohgiraffers/mergyping/user/controller/AdminNoticeController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminNoticeMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminNoticeDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminNoticeService.java
  src/main/resources/mappers/AdminNoticeMapper.xml
  src/main/resources/static/css/admin/adminnotice.css
  src/main/resources/static/css/adminnotice.css
  src/main/resources/templates/user/admin/adminmanagement.html
  src/main/resources/templates/user/admin/adminnotice.html
Labels: feature

#65 [FEATURE][SELECT_POST]게시물 상세조회 및 디비 연결
  src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dto/PostDTO.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
  src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/post/post.css
  src/main/resources/templates/main/main.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/selectpost.html
Labels: feature

#67 [FEATURE][Signup]회원가입 세부사항 업그레이드
  src/main/java/com/ohgiraffers/mergyping/user/controller/SignupController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/SignupMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/SignupService.java
  src/main/resources/mappers/SignupMapper.xml
  src/main/resources/static/css/login.css
  src/main/resources/static/css/signup/signupMain.css
  src/main/resources/static/images/icon/closeEye.png
  src/main/resources/static/images/icon/openEye.png
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/main/main.html
  src/main/resources/templates/user/signup/signup4.html
Labels: feature

#79 [FEATURE][PostDB/ImgBlur]게시글 상세조회 조정 및 이미지 블러처리
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
  src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/post/post.css
  src/main/resources/static/css/post/selectpost.css
  src/main/resources/templates/post/selectpost.html
Labels: feature

#77 [FEATURE][AuthEmail]이메일 인증을 통한 가입 절차
  build.gradle
  src/main/java/com/ohgiraffers/mergyping/auth/controller/EmailController.java
  src/main/java/com/ohgiraffers/mergyping/auth/model/AuthDetails.java
  src/main/java/com/ohgiraffers/mergyping/auth/model/service/EmailService.java
  src/main/java/com/ohgiraffers/mergyping/config/EmailConfig.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/SignupController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/EmailDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/EmailMessageDTO.java
  src/main/resources/static/css/signup/signupMain.css
  src/main/resources/static/images/icon/closeEye.png
  src/main/resources/static/images/icon/openEye.png
  src/main/resources/templates/user/signup/signup4.html
Labels: feature

#80 [FEATURE][MypagePasswordConfirm]마이페이지->개인정보 들어갈 때 비밀번호 입력 비동기 확인
  src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/MyPageDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
  src/main/resources/mappers/MyPageMapper.xml
  src/main/resources/static/css/mypage/mypageinfo.css
  src/main/resources/templates/main/main.html
  src/main/resources/templates/user/mypage/userinfo.html
Labels: feature

#82 [FEATURE][ScaryBtnDBConnect] 무서워요 안무서워요 비동기 db연결
  src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dto/FileUploadDTO.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
  src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/selectpost.html
  src/main/resources/templates/post/writepost.html
Labels: feature

#87 [FEATRUE][MypageModifyInformation]마이페이지 정보수정 기능 편의성 및 UI 추가
  .github/team_resources/db_script/MERGYPING.sql
  src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
  src/main/resources/mappers/MyPageMapper.xml
  src/main/resources/static/css/mypage/mypage.css
  src/main/resources/static/css/mypage/mypageinfo.css
  src/main/resources/templates/main/main.html
  src/main/resources/templates/user/mypage/useractive.html
  src/main/resources/templates/user/mypage/userinfo.html
  src/main/resources/templates/user/signup/signup4.html
Labels: feature

#89 [FEATURE}[AdminDeleteNotice]관리자 공지사항 삭제
  src/main/java/com/ohgiraffers/mergyping/user/controller/AdminNoticeController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminNoticeMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminNoticeService.java
  src/main/resources/mappers/AdminNoticeMapper.xml
  src/main/resources/static/css/admin/adminnoticedetail.css
  src/main/resources/templates/user/admin/adminnoticedetail.html
Labels: feature

#91 [FEATURE][SignupDuplicateCheck]회원가입 중복 확인
  src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/SignupController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/SignupMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/SignupService.java
  src/main/resources/mappers/SignupMapper.xml
  src/main/resources/static/css/signup/signupMain.css
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/user/signup/signup4.html
Labels: feature

#98 [FEATURE][MakeNewPost]게시물 작성 및 디비연결
  .github/team_resources/db_script/MERGYPING.sql
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dto/FileUploadDTO.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
  src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
  src/main/resources/mappers/MainMapper.xml
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/post/newpost.css
  src/main/resources/static/css/post/post.css
  src/main/resources/static/images/post/newpost/img-insert.png
  src/main/resources/templates/post/newpost.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/selectpost.html
  src/main/resources/templates/post/writepost.html
Labels: feature

#97 [FEATURE][ActivityRecordWrittenCommentConnectedDB]활동기록 작성 댓글 DB 연동
  src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/MypageCommentDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
  src/main/resources/mappers/MyPageMapper.xml
  src/main/resources/static/css/mypage/mypageactive.css
  src/main/resources/templates/user/mypage/useractive.html
Labels: feature

#103 [FEATURE][MypageConnectedDB]마이페이지 MBTI DB연동
  src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
  src/main/resources/mappers/MyPageMapper.xml
  src/main/resources/templates/main/main.html
  src/main/resources/templates/user/mypage/useractive.html
Labels: feature

#107 [FEATURE][AttendenceCheckConnectedDB]출석체크 DB연결
  src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
  src/main/resources/mappers/MyPageMapper.xml
  src/main/resources/templates/main/main.html
  uploads/bin.png
Labels: feature

#108 [FEAUTRE][SEARCHNOTICE]공지사항 검색
  src/main/java/com/ohgiraffers/mergyping/user/controller/AdminNoticeController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminNoticeMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminNoticeService.java
  src/main/resources/mappers/AdminNoticeMapper.xml
  src/main/resources/static/css/admin/adminnotice.css
  src/main/resources/templates/user/admin/adminnotice.html
Labels: feature

#110 [FEAUTRE][CONNECTIMAGEDB]이미지 서버 업로드, 데이터베이스에 경로 저장
  .github/team_resources/db_script/MERGYPING.sql
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/post/controller/StaticResourceController.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dto/PostDTO.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
  src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/templates/post/newpost.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/selectpost.html
Labels: feature

#111 [FEATURE][MypageConnectedDB]마이페이지와 등급DB 연결
  src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
  src/main/resources/mappers/MyPageMapper.xml
  src/main/resources/static/css/mypage/mypage.css
  src/main/resources/templates/main/main.html
Labels: feature

#116 [FEATURE][MbtiResult]mbti 테스트에 따른 Mbti 결과 페이지
  src/main/java/com/ohgiraffers/mergyping/mbti/controller/MbtiController.java
  src/main/java/com/ohgiraffers/mergyping/mbti/model/dao/MbtiMapper.java
  src/main/java/com/ohgiraffers/mergyping/mbti/model/dto/MbtiInfoDTO.java
  src/main/java/com/ohgiraffers/mergyping/mbti/model/dto/MbtiResultDTO.java
  src/main/java/com/ohgiraffers/mergyping/mbti/model/service/MbtiService.java
  src/main/resources/mappers/MbtiMapper.xml
  src/main/resources/templates/mbti/mbtiresult.html
  src/main/resources/templates/mbti/mbtitest.html
Labels: feature

#122 [FIX][ADMINPAGECONNECTEDURL]관리자 메인페이지 URL 연결
  src/main/java/com/ohgiraffers/mergyping/user/controller/AdminMainController.java
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/adminnotice.css
  src/main/resources/templates/user/admin/admin.html
  src/main/resources/templates/user/admin/adminmanagement.html
  src/main/resources/templates/user/admin/adminnotice.html
Labels: fix

#124 [FEATURE][SearchPost] 게시물 검색 기능
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dto/WriterNameDTO.java
  src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/post/post.css
  src/main/resources/static/uploads/2024-11-11/2024-11-11_15_1.png
  src/main/resources/static/uploads/2024-11-11/2024-11-11_15_2.png
  src/main/resources/static/uploads/2024-11-11/2024-11-11_16_1.png
  src/main/resources/static/uploads/2024-11-11/2024-11-11_16_2.png
  src/main/resources/templates/post/newpost.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/selectpost.html
Labels: feature

#133 [FEATURE][PostCategorySort]게시판 카테고리 정렬
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
  src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/post/post.css
  src/main/resources/templates/post/post.html
Labels: feature

#142 [FEATURE][ErrorPage]에러 페이지 구현
  src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/errorController.java
  src/main/resources/static/css/error.css
  src/main/resources/static/images/error/403.png
  src/main/resources/static/images/error/404.png
  src/main/resources/static/images/error/500.png
  src/main/resources/static/images/error/bar.png
  src/main/resources/static/images/error/ghost.png
  src/main/resources/static/images/error/logo.png
  src/main/resources/templates/mbti/mbtitest.html
  src/main/resources/templates/user/error/403.html
  src/main/resources/templates/user/error/404.html
  src/main/resources/templates/user/error/500.html
Labels: feature

#143 [FEATURE][PostPasingProcessing]게시물 페이징 처리
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/post/post.css
  src/main/resources/templates/post/post.html
Labels: feature

#150 [FIX][PostPasingProcessing]게시물 페이징 수정
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
  src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/templates/post/post.html
Labels: fix

#151 [FEATURE][SELECTADMINPOSTMANAGEMENT]관리자 공지사항 전체조회 & 페이지네이션 처리
  src/main/java/com/ohgiraffers/mergyping/user/controller/AdminPostController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminPostMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminPostDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminPostService.java
  src/main/resources/mappers/AdminPostMapper.xml
  src/main/resources/static/css/admin/adminpost.css
  src/main/resources/templates/user/admin/adminpost.html
Labels: feature

#155 [FEATURE][ADMINDETAILEDVIEW]관리자 게시물 상세보기
  src/main/java/com/ohgiraffers/mergyping/user/controller/AdminPostController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminPostMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminPostDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminPostService.java
  src/main/resources/mappers/AdminPostMapper.xml
  src/main/resources/static/css/admin/adminpost.css
  src/main/resources/static/css/admin/adminpostdetail.css
  src/main/resources/templates/user/admin/adminpost.html
  src/main/resources/templates/user/admin/adminpostdetail.html
Labels: feature

#157 [FEATURE][ConnectAdmin]관리자 페이지 연결
  .github/team_resources/db_script/MERGYPING.sql
  src/main/java/com/ohgiraffers/mergyping/auth/model/AuthDetails.java
  src/main/java/com/ohgiraffers/mergyping/auth/model/service/EmailService.java
  src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/FindController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/SignupController.java
  src/main/resources/static/css/login.css
  src/main/resources/static/css/search.css
  src/main/resources/static/css/signup/signupMain.css
  src/main/resources/static/images/search/auth.png
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/user/searchuser/searchId.html
  src/main/resources/templates/user/searchuser/searchId2.html
  src/main/resources/templates/user/searchuser/searchuser.html
  src/main/resources/templates/user/signup/signupconfirm.html
Labels: feature

#161 [FEATURE][ADMINPAGEDELETEPOSTFUNCTION]관리자 게시물 삭제
  src/main/java/com/ohgiraffers/mergyping/user/controller/AdminPostController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminPostMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminPostService.java
  src/main/resources/mappers/AdminPostMapper.xml
  src/main/resources/static/css/admin/adminpostdetail.css
  src/main/resources/templates/user/admin/adminpostdetail.html
Labels: feature

#166 [FEATURE][MypageProfileUploadPicture]마이페이지 프로필 사진 연동
  src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/LoginUserDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/MyPageDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
  src/main/resources/mappers/MyPageMapper.xml
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/mypage/mypageinfo.css
  src/main/resources/templates/main/main.html
  src/main/resources/templates/post/newpost.html
  src/main/resources/templates/user/mypage/useractive.html
  src/main/resources/templates/user/mypage/userinfo.html
Labels: feature

#169 [FIX][LoginFailedSettings]로그인 실패 설정 수정
  src/main/resources/static/css/login.css
  src/main/resources/static/images/login/box/1.png
  src/main/resources/static/images/login/box/2.png
  src/main/resources/static/images/login/box/3.png
  src/main/resources/static/images/login/box/4.png
  src/main/resources/static/images/login/box/5.png
  src/main/resources/static/images/login/box/6.png
  src/main/resources/static/images/login/box/7.png
  src/main/resources/static/images/login/box/login.png
  src/main/resources/static/images/login/box/loginBox.png
  src/main/resources/static/images/login/box/loginBox3.png
  src/main/resources/static/images/login/box/loginBox4.png
  src/main/resources/static/images/login/box/loginBoxLast.png
  src/main/resources/templates/auth/fail.html
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/user/admin/adminpostdetail.html
  src/main/resources/templates/user/searchuser/searchPwd.html
Labels: fix

#170 [FEATURE][ModifyComment]댓글 수정
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
  src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/templates/post/selectpost.html
Labels: feature

#168 [FEATURE][FindId]아이디 찾기
  src/main/java/com/ohgiraffers/mergyping/user/controller/FindController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/FindMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/UserMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/FindUserDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/FindService.java
  src/main/resources/mappers/FindMapper.xml
  src/main/resources/static/css/search.css
  src/main/resources/templates/user/searchuser/searchId.html
  src/main/resources/templates/user/searchuser/searchuser.html
Labels: feature

#172 [FEATURE][UserProfileImageConnectDB]게시물 프로필 사진 연동
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/post/newpost.css
  src/main/resources/templates/post/newpost.html
  src/main/resources/templates/post/selectpost.html
Labels: feature

#174 [Fix][SecuritySettings]시큐리티 수정 및 세팅
  src/main/java/com/ohgiraffers/mergyping/auth/model/AuthDetails.java
  src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
  src/main/resources/static/images/login/box/logins.png
  src/main/resources/static/images/login/login.png
  src/main/resources/templates/auth/fail.html
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/user/searchuser/searchPwd.html
Labels: fix

#175 [FIX][ADMINNOTICEFIX] 관리자 공지사항 카테고리 조회, 페이지네이션 수정
  src/main/java/com/ohgiraffers/mergyping/user/controller/AdminNoticeController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/ExceptionController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminNoticeMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminNoticeDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminNoticeDetailDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminNoticeService.java
  src/main/resources/mappers/AdminNoticeMapper.xml
  src/main/resources/static/css/admin/adminnotice.css
  src/main/resources/static/css/admin/adminnoticedetail.css
  src/main/resources/templates/user/admin/adminnotice.html
  src/main/resources/templates/user/admin/adminnoticedetail.html
Labels: fix

#182 [FEATURE][FindPassword]비밀번호 찾기 기능 구현
  src/main/java/com/ohgiraffers/mergyping/user/controller/FindController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/FindMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/FindUserDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/FindService.java
  src/main/resources/mappers/FindMapper.xml
  src/main/resources/static/css/search.css
  src/main/resources/templates/user/searchuser/searchPwd.html
  src/main/resources/templates/user/searchuser/searchuser.html
Labels: feature

#186 [FEATURE][DeleteComment]댓글 삭제
  src/main/java/com/ohgiraffers/mergyping/comment/model/dto/CommentDTO.java
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
  src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
  src/main/resources/mappers/MyPageMapper.xml
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/post/selectpost.css
  src/main/resources/templates/post/selectpost.html
Labels: feature

#193 [FEATURE][SELECTREPORTALL&PAGINATION]관리자 신고 전체조회 & 페이지네이션 처리
  src/main/java/com/ohgiraffers/mergyping/user/controller/AdminReportController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminReportMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminReportDTO.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminReportService.java
  src/main/resources/mappers/AdminReportMapper.xml
  src/main/resources/static/css/admin/adminreport.css
  src/main/resources/templates/user/admin/adminreport.html
Labels: feature

#201 [FEATURE][DETAILSELECTREPORTMODAL]관리자 신고 상세조회 모달
  src/main/resources/static/css/admin/adminreport.css
  src/main/resources/templates/user/admin/adminreport.html
Labels: feature

#207 [FEATURE][LoginBoxEvent]로그인 박스 이벤트
  src/main/java/com/ohgiraffers/mergyping/user/controller/ExceptionController.java
  src/main/resources/static/css/login.css
  src/main/resources/static/images/login/background01.png
  src/main/resources/static/images/login/background02.png
  src/main/resources/static/images/login/box/login.png
  src/main/resources/static/images/login/box/loginBox.png
  src/main/resources/static/images/login/box/loginBox3.png
  src/main/resources/static/images/login/box/loginBox4.png
  src/main/resources/static/images/login/box/loginBoxLast.png
  src/main/resources/static/images/login/login.png
  src/main/resources/static/images/login/loginbox.png
  src/main/resources/static/images/login/loginbox2.png
  src/main/resources/static/images/login/loginbox3.png
  src/main/resources/static/images/login/loginbox4.png
  src/main/resources/static/images/login/loginbox5.png
  src/main/resources/static/images/login/loginbox6.png
  src/main/resources/static/images/login/loginbox7.png
  src/main/resources/static/images/login/loginboxLast.png
  src/main/resources/static/images/login/searchbutton.png
  src/main/resources/templates/auth/fail.html
  src/main/resources/templates/auth/fail2.html
  src/main/resources/templates/auth/fail3.html
  src/main/resources/templates/auth/fail4.html
  src/main/resources/templates/auth/fail5.html
  src/main/resources/templates/auth/fail6.html
  src/main/resources/templates/auth/fail7.html
  src/main/resources/templates/auth/login.html
Labels: feature

#206 [FEATURE][ModifyFavorite]즐겨찾기 수정
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
  src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
  src/main/resources/mappers/MyPageMapper.xml
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/mypage/mypageactive.css
  src/main/resources/templates/post/selectpost.html
  src/main/resources/templates/user/mypage/useractive.html
Labels: feature

#216 [FEATURE][COMMENTLIKE ] 댓글 좋아요 및 게시글 좋아요 및 게시글 수정 삭제
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/templates/post/edit.html
  src/main/resources/templates/post/newpost.html
  src/main/resources/templates/post/selectpost.html
  src/test/java/com/ohgiraffers/mergyping/ApplicationTests.java
Labels: feature, fix

#211 [FIX][AllCSSFix]CSS 오류 및 부족한 부분 수정
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/adminmanagement.css
  src/main/resources/static/css/admin/adminnotice.css
  src/main/resources/static/css/admin/adminnoticedetail.css
  src/main/resources/static/css/admin/adminpostdetail.css
  src/main/resources/static/css/admin/adminreport.css
  src/main/resources/static/css/error.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/mainpage/intro/intro.css
  src/main/resources/static/css/mainpage/mainpage-darkmode.css
  src/main/resources/static/css/mbti.css
  src/main/resources/static/css/mypage/mypage.css
  src/main/resources/static/css/mypage/mypageactive.css
  src/main/resources/static/css/mypage/mypageinfo.css
  src/main/resources/static/css/notice/notice.css
  src/main/resources/static/css/post/newpost.css
  src/main/resources/static/css/post/post.css
  src/main/resources/static/css/post/selectpost.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/css/search.css
  src/main/resources/static/css/signup/signup.css
  src/main/resources/static/css/signup/signupMain.css
  src/main/resources/templates/main/main.html
  src/main/resources/templates/notice/selectnotice.html
  src/main/resources/templates/post/edit.html
  src/main/resources/templates/post/newpost.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/selectpost.html
  src/main/resources/templates/user/admin/admin.html
  src/main/resources/templates/user/admin/adminmanagement.html
  src/main/resources/templates/user/admin/adminnotice.html
  src/main/resources/templates/user/admin/adminnoticedetail.html
  src/main/resources/templates/user/admin/adminpost.html
  src/main/resources/templates/user/admin/adminpostdetail.html
  src/main/resources/templates/user/admin/adminreport.html
  src/main/resources/templates/user/mypage/user.html
  src/main/resources/templates/user/mypage/useractive.html
  src/main/resources/templates/user/mypage/userinfo.html
  src/main/resources/templates/user/signup/signupconfirm.html
Labels: feature

#217 [FEATURE][CommentConnectProfileImage]댓글에 프로필 이미지 연동
  src/main/java/com/ohgiraffers/mergyping/comment/model/dto/CommentDTO.java
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/post/selectpost.css
  src/main/resources/static/uploads/2024-11-16/2024-11-16_15_1.jpg
  src/main/resources/static/uploads/2024-11-16/2024-11-16_15_2.jpg
  src/main/resources/static/uploads/2024-11-16/2024-11-16_16_1.jpg
  src/main/resources/static/uploads/profile/17_les1211.jpg
  src/main/resources/static/uploads/profile/6_test.jpg
  src/main/resources/templates/post/selectpost.html
Labels: feature, fix

#232 [FIX][MypageConnectAll]마이페이지 네비바 있는 곳에서 전부 이용 가능하게 연결
  src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/mergyping/mbti/controller/MbtiController.java
  src/main/java/com/ohgiraffers/mergyping/notice/controller/NoticeController.java
  src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/IntroController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
  src/main/resources/mappers/MyPageMapper.xml
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/mypage/mypage.css
  src/main/resources/static/css/mypage/mypageactive.css
  src/main/resources/static/css/post/selectpost.css
  src/main/resources/templates/main/intro/intro.html
  src/main/resources/templates/main/main.html
  src/main/resources/templates/mbti/mbtiresult.html
  src/main/resources/templates/mbti/mbtistart.html
  src/main/resources/templates/mbti/mbtitest.html
  src/main/resources/templates/notice/notice.html
  src/main/resources/templates/notice/selectnotice.html
  src/main/resources/templates/post/newpost.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/selectpost.html
  src/main/resources/templates/user/mypage/useractive.html
Labels: fix

#222 [FEATURE][BestPostConnectMain]메인 베스트 게시판 연결
  src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/MainDTO.java
  src/main/resources/mappers/MainMapper.xml
  src/main/resources/static/css/login.css
  src/main/resources/static/css/mainpage/mainpage-darkmode.css
  src/main/resources/static/css/search.css
  src/main/resources/static/images/login/loginbox7.png
  src/main/resources/static/images/main/best/best.png
  src/main/resources/static/images/main/best/best2.png
  src/main/resources/static/images/main/best/best3.png
  src/main/resources/static/images/main/best/best4.png
  src/main/resources/static/images/main/main2-best.png
  src/main/resources/templates/auth/fail.html
  src/main/resources/templates/main/main.html
Labels: feature

#228 [FIX][AddIntro]인트로 내용 추가 및 CSS 문제 수정
  src/main/resources/static/css/mainpage/intro/intro.css
  src/main/resources/static/images/intro/intro.png
  src/main/resources/static/images/intro/people.png
  src/main/resources/static/images/intro/person.png
  src/main/resources/templates/main/intro/intro.html
Labels: fix

#230 [FEATURE][LevelInfo]레벨별 등급표
  src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/mergyping/level/controller/LevelController.java
  src/main/resources/static/css/level.css
  src/main/resources/static/images/level/admin.png
  src/main/resources/static/images/level/level1.png
  src/main/resources/static/images/level/level10.png
  src/main/resources/static/images/level/level2.png
  src/main/resources/static/images/level/level3.png
  src/main/resources/static/images/level/level4.png
  src/main/resources/static/images/level/level5.png
  src/main/resources/static/images/level/level6.png
  src/main/resources/static/images/level/level7.png
  src/main/resources/static/images/level/level8.png
  src/main/resources/static/images/level/level9.png
  src/main/resources/templates/main/main.html
  src/main/resources/templates/user/level/level.html
Labels: feature

#239 [FIX][FixMerge]병합 문제 수정
  src/main/resources/templates/post/selectpost.html
Labels: fix

#240 [FIX][MODIFYADMINFRONT]관리자 css수정
  src/main/java/com/ohgiraffers/mergyping/report/controller/ReportController.java
  src/main/java/com/ohgiraffers/mergyping/report/model/dao/ReportMapper.java
  src/main/java/com/ohgiraffers/mergyping/report/model/dto/ReportDTO.java
  src/main/java/com/ohgiraffers/mergyping/report/model/service/ReportService.java
  src/main/resources/mappers/ReportMapper.xml
  src/main/resources/static/css/admin/adminmanagement.css
  src/main/resources/static/css/admin/adminnotice.css
  src/main/resources/static/css/admin/adminpost.css
  src/main/resources/templates/user/admin/adminmanagement.html
  src/main/resources/templates/user/admin/adminnotice.html
Labels: fix

#243 [FIX][FixAll]병합 문제 해결
  src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/mergyping/level/controller/LevelController.java
  src/main/resources/static/css/level.css
  src/main/resources/static/images/level/admin.png
  src/main/resources/static/images/level/level1.png
  src/main/resources/static/images/level/level10.png
  src/main/resources/static/images/level/level2.png
  src/main/resources/static/images/level/level3.png
  src/main/resources/static/images/level/level4.png
  src/main/resources/static/images/level/level5.png
  src/main/resources/static/images/level/level6.png
  src/main/resources/static/images/level/level7.png
  src/main/resources/static/images/level/level8.png
  src/main/resources/static/images/level/level9.png
  src/main/resources/templates/main/main.html
  src/main/resources/templates/user/level/level.html
Labels: fix

#244 [FIX][FixErrorPage]에러페이지 작동문제 해결
  src/main/java/com/ohgiraffers/mergyping/user/controller/CustomErrorController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/ExceptionController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/IntroController.java
  src/main/resources/static/css/error.css
Labels: fix

#245 [FIX][SEARCHNOTICE] 공지사항 검색
  src/main/java/com/ohgiraffers/mergyping/notice/controller/NoticeController.java
  src/main/java/com/ohgiraffers/mergyping/notice/model/service/NoticeService.java
  src/main/resources/static/css/notice/notice.css
  src/main/resources/templates/notice/notice.html
  src/main/resources/templates/user/admin/adminpostdetail.html
Labels: fix

#247 [FIX][FixMerge]병합 문제 수정
  src/main/java/com/ohgiraffers/mergyping/user/controller/IntroController.java
  src/main/resources/templates/post/selectpost.html
Labels: fix

#250 [FIX][AddIntro]인트로 내용 추가 및 CSS 수정
  src/main/resources/static/css/intro/intro.css
  src/main/resources/templates/intro/intro.html
Labels: fix

#248 [FIX][FixRevert]되돌리기용
  src/main/resources/templates/user/signup/signupterms.html
Labels: fix

#249 [FIX][RevertFix]되돌리기용
  src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dto/MainDTO.java
  src/main/resources/mappers/MainMapper.xml
  src/main/resources/static/css/login.css
  src/main/resources/static/css/mainpage/mainpage-darkmode.css
  src/main/resources/static/css/search.css
  src/main/resources/static/images/login/loginbox7.png
  src/main/resources/static/images/main/best/best.png
  src/main/resources/static/images/main/best/best2.png
  src/main/resources/static/images/main/best/best3.png
  src/main/resources/static/images/main/best/best4.png
  src/main/resources/static/images/main/main2-best.png
  src/main/resources/templates/auth/fail.html
  src/main/resources/templates/main/main.html
Labels: fix

#253 [FIX][ADMIN]관리자 페이지 수정
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/adminpostdetail.css
  src/main/resources/templates/user/admin/admin.html
  src/main/resources/templates/user/admin/adminmanagement.html
  src/main/resources/templates/user/admin/adminnotice.html
  src/main/resources/templates/user/admin/adminnoticedetail.html
  src/main/resources/templates/user/admin/adminpost.html
  src/main/resources/templates/user/admin/adminpostdetail.html
  src/main/resources/templates/user/admin/adminreport.html
Labels: fix

#254 [FEATURE][LightMode]인트로 라이트 모드 프론트 영역 구현
  src/main/resources/static/css/intro/intro-dark.css
  src/main/resources/static/css/intro/intro-light.css
  src/main/resources/static/css/mainpage/mainpage-darkmode.css
  src/main/resources/static/css/mainpage/mainpage-lightmode.css
  src/main/resources/templates/intro/intro.html
Labels: feature, fix

#260 [FEAUTRE][ADMINPROFIE]관리자 프로필사진
  src/main/java/com/ohgiraffers/mergyping/user/controller/AdminMainController.java
  src/main/java/com/ohgiraffers/mergyping/user/model/dao/UserMapper.java
  src/main/java/com/ohgiraffers/mergyping/user/model/service/UserService.java
  src/main/resources/mappers/NoticeMapper.xml
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/uploads/profile/6_test.png
  src/main/resources/templates/user/admin/admin.html
Labels: feature

#263 [FIX][FixDetails]빨간 아이콘 로딩 문제 수정
  src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/CustomErrorController.java
  src/main/java/com/ohgiraffers/mergyping/user/controller/ExceptionController.java
  src/main/resources/templates/comment/comment.html
  src/main/resources/templates/intro/intro.html
  src/main/resources/templates/main/main.html
  src/main/resources/templates/notice/notice.html
  src/main/resources/templates/notice/selectnotice.html
  src/main/resources/templates/post/edit.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/selectpost.html
Labels: fix
